name: Publish to CurseForge & Modrinth

on:
  release:
    types: [created]

env:
  MINECRAFT_VERSION: 1.19.2
  JAVA_VERSION: 17
  VERSION: ${{ github.event.release.tag_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 906667
          curseforge-token: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}

          modrinth-id: 7fuceqNZ
          modrinth-token: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}

          name: Miraculous Miracles ${{ env.VERSION }} for Minecraft ${{ env.MINECRAFT_VERSION }}
          version: ${{ env.VERSION }}
          version-type: alpha
          changelog: ${{ github.event.release.body }}
          dependencies: |
            qsl@4.0.0-beta.30+0.76.0-1.19.2(required)
            qkl@1.0.2(required)
            patchouli@1.19.2-77-fabric(optional){curseforge:393236}

          loaders: quilt
          game-versions: ${{ env.MINECRAFT_VERSION }}
          java: ${{ env.JAVA_VERSION }}
